name: architecture_template_v2
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  #Core
  equatable: ^2.0.5

  #Network
  vexana: ^3.5.4

  #State
  flutter_riverpod: ^2.4.5

  #Config
  easy_localization: ^3.0.3

  #Utility
  kartal: ^3.5.0
  envied: ^0.3.0+3

  #Module
  core:
    path: module/core
#dependencies_overrides:

dev_dependencies:
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.2
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  json_annotation: ^4.8.1

  very_good_analysis: ^5.1.0

flutter_gen:
  output: lib/product/generated
  integrations: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app/app_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - asset/translations/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
